[32mINFO    [0m root:test_task_post.py:28 Executing Incomplete Task API
[32mINFO    [0m root:test_task_post.py:29 Sending the POST request with task id gEmeh3OF
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks/gEmeh3OF/incomplete HTTP/1.1" 200 2
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "GET /tasks/gEmeh3OF HTTP/1.1" 200 39
[32mINFO    [0m root:test_task_post.py:31 Task status completed False